### ISSUE TITLE
Boards Announcement

### ISSUE THREAD

**Issue by amanloc1** [Navprayas-A-group-of-Innovative-thought/Navprayas-Frontend#10]
![Boards](https://user-images.githubusercontent.com/48627031/90132723-f3480f00-dd8b-11ea-8aab-9e6131a37250.png)
 

Do only Announcement part

**Comment by naina24** [comment]
interested

**Comment by rahulheritage22** [comment]
interested

**Comment by amanloc1** [comment]
update a screenshot of your work
