### ISSUE TITLE
Boards quick links

### ISSUE THREAD

**Issue by amanloc1** [Navprayas-A-group-of-Innovative-thought/Navprayas-Frontend#11]
![Boards](https://user-images.githubusercontent.com/48627031/90132934-44f09980-dd8c-11ea-9e36-1be97c2732f9.png)

Do only quick link part

**Comment by naina24** [comment]
interested

**Comment by naina24** [comment]
![NavScreen](https://user-images.githubusercontent.com/57555177/90308240-85225a00-defb-11ea-8b4f-07b861dfcbe7.png)

**Comment by naina24** [comment]
bhaiya is it ok??

**Comment by amanloc1** [comment]
For now it's okay ... If there will be some changes required will convey you to the same

**Comment by kmrakash** [comment]
@naina24  please create a Pull request for the same
