### ISSUE TITLE
Login screen

### ISSUE THREAD

**Issue by amanloc1** [Navprayas-A-group-of-Innovative-thought/Navprayas-Frontend#18]
![login screen](https://user-images.githubusercontent.com/48627031/90174468-a8e28480-ddc3-11ea-8aca-bade3fefa27c.jpg)

**Comment by rahulheritage22** [comment]
interested

**Comment by Saggittarius-A** [comment]
interested

**Comment by amanloc1** [comment]
rahul tum pahle se hi ek task kar rhe ho to maine yeh task shruti ko de diya hai

**Comment by rahulheritage22** [comment]
ok no problem

**Comment by Saggittarius-A** [comment]
i was trying to create a pull request but thee was error showing cant accept the reqjest for git clone

**Comment by amanloc1** [comment]
Is your problem solved? First try reaching to the whatsapp group for any doubts as i may be not available all the time.
