### ISSUE TITLE
Header Component

### ISSUE THREAD

**Issue by amanloc1** [Navprayas-A-group-of-Innovative-thought/Navprayas-Frontend#3]
Make Header component as done in the assignment phase.

**Comment by amanloc1** [comment]
![header](https://user-images.githubusercontent.com/48627031/90128678-e116a280-dd84-11ea-9f82-5c3a0d2725ac.jpg)

![header (1)](https://user-images.githubusercontent.com/48627031/90129232-e7594e80-dd85-11ea-94f5-4b1c76ad9c96.jpg)

dono header ka alignment thoda alag alag hai isme lekin wsa hoga nahi

**Comment by kmrakash** [comment]
Acha ek bar fr se yahi mention kr dete kon kon sa drop-down hoga aur dropdown me kiya kiya likhna hai wo

**Comment by amanloc1** [comment]
ok will mention it later after few hours
