### ISSUE TITLE
Carousel for home screen

### ISSUE THREAD

**Issue by amanloc1** [Navprayas-A-group-of-Innovative-thought/Navprayas-Frontend#5]
make main section as done in assignment phase.

**Comment by kmrakash** [comment]
This will be our carausel section . Since we are using reactstrap . I'm adding documentation for your help [here](https://reactstrap.github.io/components/carousel/)
Try using some dummies pictures while development .

**Comment by amanloc1** [comment]
![carousel](https://user-images.githubusercontent.com/48627031/90132130-dfe87400-dd8a-11ea-9ab5-7fdb5d79ada8.jpg)

**Comment by muskan89** [comment]
interested

**Comment by muskan89** [comment]
![Screenshot (143)](https://user-images.githubusercontent.com/67742819/90339683-e2a7cb00-e00f-11ea-94ac-e878fc3114d3.png)

**Comment by muskan89** [comment]
![Screenshot (144)](https://user-images.githubusercontent.com/67742819/90342497-6371c180-e026-11ea-84e8-facfaa5c877e.png)
![Screenshot (145)](https://user-images.githubusercontent.com/67742819/90342506-71274700-e026-11ea-8d6c-63cbc5f8fcb2.png)
![Screenshot (146)](https://user-images.githubusercontent.com/67742819/90342508-75ebfb00-e026-11ea-911f-20bb2f1456c3.png)
